jms_translation:
    configs:
        app:
            dirs: ["%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations/api"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
